### ISSUE TITLE
Pyqtgraph plotter in McStas 2.6.1 and McXtrace 1.5 misbehaves on Ubuntu 20.04

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1022]
When shifting from overview plot to a single monitor, "stripes" from the overview plot remain on top of the subplot:

![Screenshot 2020-05-27 at 11 25 38](https://user-images.githubusercontent.com/8593355/83003042-0f9aa200-a00e-11ea-82f5-8923516abf48.png)
![Screenshot 2020-05-27 at 11 25 50](https://user-images.githubusercontent.com/8593355/83003060-14f7ec80-a00e-11ea-8b22-6687da7ab3f0.png)
![Screenshot 2020-05-27 at 11 29 57](https://user-images.githubusercontent.com/8593355/83003068-16c1b000-a00e-11ea-9326-60d0e346b608.png)

Was initially thought to be an X-forwarding issue in the new dockers only, but is the same on a "normal" Ubuntu 20.04 desktop.

Changes in pyqtgraph?

**Comment by willend** [comment]
When clicking into a subplot this error occurs on the console, could be connecte:
```
[11:50:55]  Error sending hover exit event:

    |==============================>>
    |  Traceback (most recent call last):
    |    File "/usr/share/mcstas/2.6.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 67, in <module>
    |      main(args)
    |    File "/usr/share/mcstas/2.6.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 51, in main
    |      plotter.runplot()
    |    File "/usr/share/mcstas/2.6.1/tools/Python/mcplot/pyqtgraph/../../mccodelib/pqtgfrontend.py", line 65, in runplot
    |      sys.exit(self.app.exec_())
    |    File "/usr/lib/python3/dist-packages/pyqtgraph/widgets/GraphicsView.py", line 364, in mouseReleaseEvent
    |      QtGui.QGraphicsView.mouseReleaseEvent(self, ev)
    |    File "/usr/lib/python3/dist-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 226, in mouseReleaseEvent
    |      self.sendHoverEvents(ev)  ## let items prepare for next click/drag
    |    File "/usr/lib/python3/dist-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 272, in sendHoverEvents
    |      debug.printExc("Error sending hover exit event:")
    |    --- exception caught here ---
    |    File "/usr/lib/python3/dist-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 269, in sendHoverEvents
    |      if item.scene() is self:
    |  RuntimeError: wrapped C/C++ object of type ImageItem has been deleted
    |==============================<<

```
