### ISSUE TITLE
Error message from mouseevent handler in pyqtgraph plotter

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1024]
```
[11:50:55]  Error sending hover exit event:

    |==============================>>
    |  Traceback (most recent call last):
    |    File "/usr/share/mcstas/2.6.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 67, in <module>
    |      main(args)
    |    File "/usr/share/mcstas/2.6.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 51, in main
    |      plotter.runplot()
    |    File "/usr/share/mcstas/2.6.1/tools/Python/mcplot/pyqtgraph/../../mccodelib/pqtgfrontend.py", line 65, in runplot
    |      sys.exit(self.app.exec_())
    |    File "/usr/lib/python3/dist-packages/pyqtgraph/widgets/GraphicsView.py", line 364, in mouseReleaseEvent
    |      QtGui.QGraphicsView.mouseReleaseEvent(self, ev)
    |    File "/usr/lib/python3/dist-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 226, in mouseReleaseEvent
    |      self.sendHoverEvents(ev)  ## let items prepare for next click/drag
    |    File "/usr/lib/python3/dist-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 272, in sendHoverEvents
    |      debug.printExc("Error sending hover exit event:")
    |    --- exception caught here ---
    |    File "/usr/lib/python3/dist-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 269, in sendHoverEvents
    |      if item.scene() is self:
    |  RuntimeError: wrapped C/C++ object of type ImageItem has been deleted
    |==============================<<

```

**Comment by willend** [comment]
Occurs on return from subplot to overview

**Comment by willend** [comment]
Annoyingly it looks like Ubuntu have packaged an "rc" labled package for 20.04:
```
dpkg -l python3-pyqtgraph
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version      Architecture Description
+++-=================-============-============-================================================
ii  python3-pyqtgraph 0.11.0~rc0-1 all          Scientific Graphics and GUI Library for Python 3
```
- whereas e.g. 18.04 ships 
```
ii  python3-pyqtgraph 0.10.0-1 all          Scientific Graphics and GUI Library for Python 
```

If one downgrades e.g. by use of pip (that also distribute the older package) the issue goes away.

**Comment by farhi** [comment]
Fixed in modern systems
