### ISSUE TITLE
plot-pyqtgraph: fails with Python 3.10

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#1281]
When plotting any mcstas/mcxtrace simulation, the mcplot/mxplot fails when using the default pyqtgraph renderer:
```python
mxplot Test_Sqw_20220922_114217
loading system configuration

q              - quit
p              - save png
s              - save svg
l              - log toggle
t              - textinfo toggle
c              - cycle colormap
F1/h           - help
F5             - replot
click          - display subplot
right-click/b  - back
ctrl + click   - sweep monitors
x              - expand subplots
mcplot error: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'float'
  resize(self, int, int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "/usr/share/mcxtrace/1.7/bin/../tools/Python/mxplot/pyqtgraph/mxplot.py", line 67, in <module>
    main(args)
  File "/usr/share/mcxtrace/1.7/bin/../tools/Python/mxplot/pyqtgraph/mxplot.py", line 57, in main
    raise e
  File "/usr/share/mcxtrace/1.7/bin/../tools/Python/mxplot/pyqtgraph/mxplot.py", line 51, in main
    plotter.runplot()
  File "/usr/share/mcxtrace/1.7/tools/Python/mxplot/pyqtgraph/../../mccodelib/pqtgfrontend.py", line 56, in runplot
    plt_layout = create_plotwindow(title=self.sourcedir+" - Press 'h' for app shortcuts")
  File "/usr/share/mcxtrace/1.7/tools/Python/mxplot/pyqtgraph/../../mccodelib/pqtgfrontend.py", line 82, in create_plotwindow
    mw.resize(w, h)
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'float'
  resize(self, int, int): argument 1 has unexpected type 'float'
```

It may be related to new 'float' types now part of core python. The np.float should not be used, or be changed into e.g. np.float32.
In short this looks like a casting issue with py 3.10

**Comment by willend** [comment]
Hi @farhi,

I believe this is in fact already covered (and fixed) via the patches @g5t supplied in https://github.com/McStasMcXtrace/McCode/issues/1270 ?

(I believe I fixed the code both on mccode-3 and master already)

**Comment by willend** [comment]
https://github.com/McStasMcXtrace/McCode/commit/279744c0a00d9cafae9f84347a770faafae874d2

**Comment by willend** [comment]
@farhi please try replacing your 

```$MCXTRACE/tools/Python/mccodelib/pqtgfrontend.py``` 
with that of the repo, please also consider replacing 

```$MCXTRACE/tools/Python/mxgui/viewclasses.py```

- as mentioned for McStas in https://github.com/McStasMcXtrace/McCode/issues/1271
