### ISSUE TITLE
Problem mcdisplay-webgl (and show_instrument())

### ISSUE THREAD

**Issue by riwa73** [McStasMcXtrace/McCode#1426]
In the latest McStas Version (Release 3.3)
an exception is raised from the execution of  _mcdisplay-webgl.py_.
Its a **shutil.SameFileError** (see below): 

``` 
Traceback (most recent call last):
  File "/Applications/McStas-3.3.app/Contents/Resources/mcstas/3.3/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 195, in <module>
    main(**args)
  File "/Applications/McStas-3.3.app/Contents/Resources/mcstas/3.3/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 167, in main
    write_browse(instrument, raybundle, dirname, instr, **kwds)
  File "/Applications/McStas-3.3.app/Contents/Resources/mcstas/3.3/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 133, in write_browse
    shutil_copy(instrname, str(dest.joinpath(instrname)))
  File "/Applications/McStas-3.3.app/Contents/Resources/mcstas/3.3/miniconda3/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Applications/McStas-3.3.app/Contents/Resources/mcstas/3.3/miniconda3/lib/python3.10/shutil.py", line 234, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/Users/wagnerrichard/owncloud_ILL/JupyterHome/NNBAR/run_folder/Mcstasscript_minimal_test_ver1.instr' and '/Users/wagnerrichard/owncloud_ILL/JupyterHome/NNBAR/run_folder/Mcstasscript_minimal_test_ver1.instr' are the same file
wagnerrichard@wagnermini NNBAR % "/Applications/McStas-3.3.app/Contents/Resources/mcstas/3.3/bin/mcdisplay-webgl" --dirname test --nobrowse /Users/wagnerrichard/owncloud_ILL/JupyterHome/NNBAR/run_folder/Mcstasscript_minimal_test_ver1.instr
```
This problem arises if McStas is used with Mcstasscript and if _mcdisplay-webgl_ is called with the full path to an instrument file.  

I found a workaround:
I made a change in the _write_browse()_ function before the call of _shutil_copy()_ in Line 133 of _mcdisplay.py_

```
    temp_instrname = Path(instrname)
    instrname = temp_instrname.name

    shutil_copy(instrname, str(dest.joinpath(instrname)))
```
With this adaption the call to _shutil_copy()_ succeeds and the webgl visualisation of the instrument is opened in the browser.

**Comment by willend** [comment]
@riwa73 thanks for reporting. Does your remark

> This problem arises if McStas is used with Mcstasscript and if mcdisplay-webgl is called with the full path to an instrument file.

indicate that the problem does no occur if using relative paths?

**Comment by riwa73** [comment]
yes, using relative paths it works.
