### ISSUE TITLE
Plot: PyQtGraph: click on single monitor plots fails

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#1582]
When running a simulation and plotting results, a click on any part of the PyQtGraph window brings an error:
```python
Traceback (most recent call last):
  File "/usr/share/mcxtrace/3.4-20240304/tools/Python/mxplot/pyqtgraph/../../mccodelib/pqtgfrontend.py", line 388, in <lambda>
    lambda event: click_handler(
                  ^^^^^^^^^^^^^^
  File "/usr/share/mcxtrace/3.4-20240304/tools/Python/mxplot/pyqtgraph/../../mccodelib/pqtgfrontend.py", line 367, in click_handler
    if int(event.modifiers()) != mod:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'KeyboardModifier'
```

**Comment by willend** [comment]
I am afraid the key-modifier stuff needs to be in place courtesy of Windows and macOS - the last commit here renders clicking on the main ui not functional on these systems....
