### ISSUE TITLE
Mc/MxGUI: the item "Simulation/Plot Other Results" crashes

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#1583]
Just opening mxgui/mcgui and selecting the "Simulation/Plot Other Results" make the window fully crash with an error in the Terminal:
```python
Traceback (most recent call last):
  File "/usr/share/mcxtrace/3.4-20240304/tools/Python/mxgui/mxgui.py", line 703, in handlePlotOtherResults
    resultdir = self.view.showOpenPlotDirDlg(os.getcwd())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/mcxtrace/3.4-20240304/tools/Python/mxgui/viewclasses.py", line 166, in showOpenPlotDirDlg
    dlg.ShowDirsOnly
AttributeError: 'QFileDialog' object has no attribute 'ShowDirsOnly'
/usr/bin/mxgui : ligne 88 : 86926 Abandon                 python3 -u ${UTILDIR}/${TOOL}.py $*
```

**Comment by farhi** [comment]
The opening via the command mxplot/mcplot works.
