### ISSUE TITLE
Current main branch MPI settings for Windows are Visual C specific

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1588]
If using gcc on Windows the current mpi settings are wrong:

```
(base) C:\Users\pkwi\SE_example2>gcc -o SE_example2.exe SE_example2.c -lm /DUSE_MPI /LINK /DYNAMICBASE msmpi             -g -O2 -DNDEBUG -lm -std=c99 -D_POSIX_SOURCE -lmsmpi -IC:\mcstas-3.4.25\bin\\..\miniconda3\Library\Include -L"C:\mcstas-3.4.25\bin\\..\miniconda3\Library\lib
gcc: error: /DUSE_MPI: No such file or directory
gcc: error: /LINK: No such file or directory
gcc: error: /DYNAMICBASE: No such file or directory
gcc: error: msmpi: No such file or directory
INFO: call to mpicc.bat failed with Command 'mpicc.bat -o SE_example2.exe SE_example2.c -lm /DUSE_MPI /LINK /DYNAMICBASE msmpi             -g -O2 -DNDEBUG -lm -std=c99 -D_POSIX_SOURCE' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\mcstas-3.4.25\lib\tools\Python\mcrun\mcrun.py", line 569, in <module>
    main()
  File "C:\mcstas-3.4.25\lib\tools\Python\mcrun\mcrun.py", line 483, in main
    mcstas.prepare(options)
  File "C:\mcstas-3.4.25\lib\tools\Python\mcrun\mccode.py", line 245, in prepare
    Process(lexer.quote(options.cc)).run(args)
  File "C:\mcstas-3.4.25\lib\tools\Python\mcrun\mccode.py", line 77, in run
    raise err
  File "C:\mcstas-3.4.25\lib\tools\Python\mcrun\mccode.py", line 73, in run
    proc = run(command, shell=True, check=True, text=True, capture_output=pipe)
  File "c:\mcstas-3.4.25\miniconda3\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mpicc.bat -o SE_example2.exe SE_example2.c -lm /DUSE_MPI /LINK /DYNAMICBASE msmpi             -g -O2 -DNDEBUG -lm -std=c99 -D_POSIX_SOURCE' returned non-zero exit status 1.
```

We need a build-time config option (perhaps for now via `-DMCCODE_BUILD_CONDA_PKG=ON/OFF`) to configure for `cl.exe` or `gcc.exe` style parameters

**Comment by willend** [comment]
Very simple in fact - for `gcc.exe` we simply need `-DUSE_MPI -lmsmpi`
