### ISSUE TITLE
Matplotlib mcplot numpy

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1752]
At least via conda, the matplotlib plotter may need an overhaul if it is to survive...

```
mcplot-matplotlib --invcanvas HEIMDAL_full_TCS_20241024_161327/Lambda_before_ResChopper.dat 

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<string>", line 1, in <module>
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/ticker.py", line 143, in <module>
    from matplotlib import transforms as mtransforms
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/ticker.py", line 143, in <module>
    from matplotlib import transforms as mtransforms
  File "/Users/peterwillendrup/miniforge3/lib/python3.10/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
button returned:OK
```

**Comment by willend** [comment]
It seems that on the affected system numpy arrived via pip - uninstalling that and `conda install numpy=1.26.4` seemed to fit the issue.
