### ISSUE TITLE
HEAD version mcgui-py has runtime issue relating to exception handling 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#182]
Found this morning on OS X @jaga-mcstas - happens only in the 'trace' mode it seems?

    2015-11-12 09:33:14.703 python[35191:1098519] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
    2015-11-12 09:33:24.793 python[35191:1098519] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
    Running: mcdisplay-matplotlib-py /Users/pkwi/tmp/Backscattering/IN_13.instr --no-output-files  -n 1000000 RMV=0 RDV=4.6 RDH=0 TM=301 LMD=1.8 mos_ana=2 CaF2mos=10 gW=0.03
    Traceback (most recent call last):
    File "/Applications/McStas-2.3.app/Contents/Resources/mcstas/2.3/tools/Python/mcgui/mcgui.py", line 551, in handleRunOrInterruptSim
    self.state.run(fixed_params, new_instr_params)
    File "/Applications/McStas-2.3.app/Contents/Resources/mcstas/2.3/tools/Python/mcgui/mcgui.py", line 390, in run
    self.__runthread.thread_exception.connect(handleExceptionMsg)
    NameError: global name 'handleExceptionMsg' is not defined

**Comment by willend** [comment]
Seems to have been fixed, DONE
