### ISSUE TITLE
McStas: mcplot-gnuplot-py on Windows 8 (my virtual machine), not plotting

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#278]
Hi @climbcat,

No hurry since there are other solutions, but I have the following behaviour of mcplot-gnuplot-py on Windows:

<pre>
C:\Users\Peter>python c:\mcstas-2.3\lib\tools\Python\mcplot\gnuplot\mcplot.py BN
L_H8.exe_20150429_071510
Using sim file: C:\Users\Peter\BNL_H8.exe_20150429_071510\mccode.sim
Loading C:\Users\Peter\BNL_H8.exe_20150429_071510\D0_Source.psd
Loading C:\Users\Peter\BNL_H8.exe_20150429_071510\D1_SC1_Out.psd
Loading C:\Users\Peter\BNL_H8.exe_20150429_071510\D2_A4.psd
Loading C:\Users\Peter\BNL_H8.exe_20150429_071510\D4_SC2_In.psd
Loading C:\Users\Peter\BNL_H8.exe_20150429_071510\D5_SC2_Out.psd
Loading C:\Users\Peter\BNL_H8.exe_20150429_071510\D7_SC3_In.psd
Loading C:\Users\Peter\BNL_H8.exe_20150429_071510\D8_SC3_Out.psd
Loading C:\Users\Peter\BNL_H8.exe_20150429_071510\D10_SC4_In.psd
Loading C:\Users\Peter\BNL_H8.exe_20150429_071510\He3.psd
Traceback (most recent call last):
  File "c:\mcstas-2.3\lib\tools\Python\mcplot\gnuplot\mcplot.py", line 72, in <m
odule>
    main(args)
  File "c:\mcstas-2.3\lib\tools\Python\mcplot\gnuplot\mcplot.py", line 31, in ma
in
    plotter = McGnuplotter(simulation, noqt=args.noqt, log_scale=args.logscale)
  File "c:\mcstas-2.3\lib\tools\Python\mcplot\gnuplot\mcgnuplotter.py", line 221
, in __init__
    self.setLogscale(log_scale)
  File "c:\mcstas-2.3\lib\tools\Python\mcplot\gnuplot\mcgnuplotter.py", line 257
, in setLogscale
    self.__gnuplot_objs[key].setLog(log_scale)
  File "c:\mcstas-2.3\lib\tools\Python\mcplot\gnuplot\mcgnuplotter.py", line 48,
 in setLog
    self.setLog_impl(self.gp, log_scale)
  File "c:\mcstas-2.3\lib\tools\Python\mcplot\gnuplot\mcgnuplotter.py", line 137
, in setLog_impl
    gp('unset logscale y')
  File "C:\Users\Peter\Anaconda2\lib\site-packages\Gnuplot\_Gnuplot.py", line 21
0, in __call__
    self.gnuplot(s)
  File "C:\Users\Peter\Anaconda2\lib\site-packages\Gnuplot\gp_win32.py", line 13
0, in __call__
    self.write(s + '\n')
IOError: [Errno 22] Invalid argument
</pre>

Gnuplot is found OK on the path.

**Comment by willend** [comment]
Aiming toward pyqtgraph as a common solutiuon -gnuplot may become obsoleted
