### ISSUE TITLE
mcgui-py: Ncounts should be accepted in scientific notation

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#303]
Currently, only literal 100000 is accepted - not 1e5.

**Comment by willend** [comment]
Exact error message is
<pre>
Traceback (most recent call last):
  File "/Applications/McStas-2.4rc0.app/Contents/Resources/mcstas/2.4rc0/tools/Python/mcgui/mcgui.py", line 585, in handleRunOrInterruptSim
    self.state.run(fixed_params, new_instr_params)
  File "/Applications/McStas-2.4rc0.app/Contents/Resources/mcstas/2.4rc0/tools/Python/mcgui/mcgui.py", line 370, in run
    if int(ncount) > 0:
ValueError: invalid literal for int() with base 10: '1e6'
</pre>
