### ISSUE TITLE
mxplot-gnuplot-py dies when a data filename starts with a number

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#307]
When the data file of a monitor is named something with a number first (in my test "4pi.dat") 
mxplot-gnuplot-py dies with 
Traceback (most recent call last):
  File "/home/erkn/mcxtrace/2.9999-svn/tools/Python/mxplot/gnuplot/mcplot.py", line 72, in <module>
    main(args)
  File "/home/erkn/mcxtrace/2.9999-svn/tools/Python/mxplot/gnuplot/mcplot.py", line 61, in main
    exec('mcgnuview.startGui(plotter, log_scale=args.logscale)')
  File "<string>", line 1, in <module>
  File "/home/erkn/mcxtrace/2.9999-svn/tools/Python/mxplot/gnuplot/mcgnuview.py", line 17, in startGui
    mediator.initUi(log_scale)
  File "/home/erkn/mcxtrace/2.9999-svn/tools/Python/mxplot/gnuplot/mcgnuview.py", line 31, in initUi
    self.__mcgv.initUi(self.__plotter.getDataKeys(), log_scale)
  File "/home/erkn/mcxtrace/2.9999-svn/tools/Python/mxplot/gnuplot/mcgnuplotter.py", line 262, in getDataKeys
    return sorted(self.__gnuplot_objs.keys(), key=lambda item: (int(item.partition(' ')[0])
  File "/home/erkn/mcxtrace/2.9999-svn/tools/Python/mxplot/gnuplot/mcgnuplotter.py", line 263, in <lambda>
    if item[0].isdigit() else float('inf'), item))
ValueError: invalid literal for int() with base 10: '4pi.dat'

If I manually edit the filename to e.g. "psd4pi.dat" (and also in mccode.sim) the plotter works fine.

**Comment by climbcat** [comment]
Seems to be fixed now.

**Comment by climbcat** [comment]
A new problem: the overview is no longer at the top of the list.
