### ISSUE TITLE
Check status of python3 support in the tools

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#329]
Currently mcgui and mcrun are packaged and works with python3 on Debian.

We should:
* Check which other of the existing py-tools that are python3 ready, for instance the matplotlib mcdisplay is not - see below
* Build an test on an rpm-distro to find proper naming of the dependencies 

<pre>
mcstas@mcstas-virtual-machine:~/McCode/tools/Python/mcdisplay/matplotlib$ python mcdisplay.py 
^CTraceback (most recent call last):
  File "mcdisplay.py", line 192, in <module>
    parse_trace()
  File "mcdisplay.py", line 68, in parse_trace
    line = get_line()
  File "/home/mcstas/McCode/tools/Python/mcdisplay/matplotlib/util.py", line 70, in get_line
    return stdin.readline().strip()
KeyboardInterrupt
mcstas@mcstas-virtual-machine:~/McCode/tools/Python/mcdisplay/matplotlib$ python3 mcdisplay.py 
Traceback (most recent call last):
  File "mcdisplay.py", line 11, in <module>
    from util import parse_multiline, rotate, rotate_points, draw_circle, get_line, debug
  File "/home/mcstas/McCode/tools/Python/mcdisplay/matplotlib/util.py", line 22
    def rotate(point, (origin, rotm)):
                      ^
SyntaxError: invalid syntax
mcstas@mcstas-virtual-machine:~/McCode/tools/Python/mcdisplay/matplotlib$
</pre>

**Comment by willend** [comment]
Consider to make some of all these options obsolete...

**Comment by willend** [comment]
Obsoleted some tools - would still work with a Python 2.7 of course, but better solutions are under way.

mcplot-matplotlib has been ported to Python 3.

Closing this issue.
