### ISSUE TITLE
Python3 + mcdisplay-webgl issue when parms / --default not given

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#348]
<pre>
mcdisplay-webgl-py templateSANS.instr 
mcrun: reading local mcstas configuration from /Users/pkwi/.mcstas/mccode_config.perl
/Applications/McStas-2.4rc05.app/Contents/Resources/mcstas/2.4rc05/tools/Python/mcdisplay/webgl/../../mccodelib/../../../bin/mcrun: reading local mcstas configuration from /Users/pkwi/.mcstas/mccode_config.perl
Running simulation 'templateSANS.out' ...
templateSANS.out --trace --dir=templateSANS_20161123_151901 --format=PGPLOT --ncount=100
Instrument parameters for templateSANS (templateSANS.instr)
Set value of instrument parameter lambda (double) [default='6']:
name 'raw_input' is not defined
Traceback (most recent call last):
  File "/Applications/McStas-2.4rc05.app/Contents/Resources/mcstas/2.4rc05/tools/Python/mcdisplay/webgl/mcdisplay.py", line 185, in <module>
    raise e
  File "/Applications/McStas-2.4rc05.app/Contents/Resources/mcstas/2.4rc05/tools/Python/mcdisplay/webgl/mcdisplay.py", line 180, in <module>
    main(args)
  File "/Applications/McStas-2.4rc05.app/Contents/Resources/mcstas/2.4rc05/tools/Python/mcdisplay/webgl/mcdisplay.py", line 150, in main
    instrument = reader.read_instrument()
  File "/Applications/McStas-2.4rc05.app/Contents/Resources/mcstas/2.4rc05/tools/Python/mcdisplay/webgl/../../mccodelib/mcdisplayutils.py", line 57, in read_instrument
    self.pipeman.join()
  File "/Applications/McStas-2.4rc05.app/Contents/Resources/mcstas/2.4rc05/tools/Python/mcdisplay/webgl/../../mccodelib/pipetools.py", line 241, in join
    raise self.reader.exc_obj
  File "/Applications/McStas-2.4rc05.app/Contents/Resources/mcstas/2.4rc05/tools/Python/mcdisplay/webgl/../../mccodelib/pipetools.py", line 205, in run
    self.current.add_line(stdoutdata)
  File "/Applications/McStas-2.4rc05.app/Contents/Resources/mcstas/2.4rc05/tools/Python/mcdisplay/webgl/../../mccodelib/pipetools.py", line 79, in add_line
    input = raw_input()
NameError: name 'raw_input' is not defined
</pre>

**Comment by climbcat** [comment]
Done.
