### ISSUE TITLE
mcplot-pyqtgraph: Issue plotting (some??) 2D datasets

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#375]
Hi there,

Using this dataset:

[Demo-fail.zip](https://github.com/McStasMcXtrace/McCode/files/716278/Demo-fail.zip)

I get the below error message on Mac OS X. I have the same issue with BNL_H8 and default parameters - and I believe that instrument uses Monitor_nD output only... (So maybe the issue stems from something that comp does in a different way than e.g. PSD_monitor...)

Best,

Peter

<pre>
Data2D load error.
mcplot error: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 404, in <module>
    main(args)
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 395, in main
    raise e
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 374, in main
    loader.load()
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 703, in load
    exit_node = control.process(args=args)
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/flowchart.py", line 86, in process
    next = node.process(args)
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/flowchart.py", line 67, in process
    self.result = self.fct(args)
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 588, in load_simulation
    data_lst = _load_data_from_mcfiles(_get_filenames_from_mccodesim(join(d, 'mccode.sim')))
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 323, in _load_data_from_mcfiles
    data = _load_monitor(f)
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 299, in _load_monitor
    data = _parse_2D_monitor(text)
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 281, in _parse_2D_monitor
    raise e
  File "/Applications/McStas-2.4rc30.app/Contents/Resources/mcstas/2.4rc30/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 226, in _parse_2D_monitor
    data.yvar = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
</pre>

**Comment by willend** [comment]
Unfortunately there are issues again after the last set of commits - the demo dataset above now breaks with

<pre>
mcplot MCPLs/W8/AutoL0_1481626261.U1 
mcplot error: Could not load file "MCPLs/W8/AutoL0_1481626261.U1".
Traceback (most recent call last):
  File "/Applications/McStas-2.4rc32.app/Contents/Resources/mcstas/2.4rc32/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 369, in <module>
    main(args)
  File "/Applications/McStas-2.4rc32.app/Contents/Resources/mcstas/2.4rc32/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 360, in main
    raise e
  File "/Applications/McStas-2.4rc32.app/Contents/Resources/mcstas/2.4rc32/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 339, in main
    loader.load()
  File "/Applications/McStas-2.4rc32.app/Contents/Resources/mcstas/2.4rc32/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 703, in load
    exit_node = control.process(args=args)
  File "/Applications/McStas-2.4rc32.app/Contents/Resources/mcstas/2.4rc32/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/flowchart.py", line 86, in process
    next = node.process(args)
  File "/Applications/McStas-2.4rc32.app/Contents/Resources/mcstas/2.4rc32/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/flowchart.py", line 67, in process
    self.result = self.fct(args)
  File "/Applications/McStas-2.4rc32.app/Contents/Resources/mcstas/2.4rc32/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 664, in throw_error
    raise Exception('Could not load file "%s".' % args['simfile'])
Exception: Could not load file "MCPLs/W8/AutoL0_1481626261.U1".
</pre>

Same colour, different flavor... ;-)

@climbcat will you have a look?

**Comment by climbcat** [comment]
Of cause=)

**Comment by climbcat** [comment]
There is no loading issue on my system (although another problem with that data set has appeared). Let's have a look next week and do some more testing in parallel.

**Comment by climbcat** [comment]
We fixed this yesterday, I believe.
