### ISSUE TITLE
New python mcdisplay's fail on windows

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#384]
<pre>
WARNING: t_ignore contains a literal backslash '\'
Generating LALR tables
Syntax error in input!
LexToken(ID,'C',2,39)
InstrObjectConstructor: parsetreeroot must be a Node of type "instrdeftree"
Traceback (most recent call last):
  File "C:\\mcstas-2.4rc40\\lib\\tools\\Python\\mcdisplay\\webgl\\mcdisplay.py", line 185, in <module>
    raise e
  File "C:\\mcstas-2.4rc40\\lib\\tools\\Python\\mcdisplay\\webgl\\mcdisplay.py", line 180, in <module>
    main(args)
  File "C:\\mcstas-2.4rc40\\lib\\tools\\Python\\mcdisplay\\webgl\\mcdisplay.py", line 150, in main
    instrument = reader.read_instrument()
  File "C:\\mcstas-2.4rc40\\lib\\tools\\Python\\mcdisplay\\webgl\..\..\mccodelib\mcdisplayutils.py", line 65, in read_instrument
    instrbuilder = InstrObjectConstructor(instrparser.parsetree)
  File "C:\\mcstas-2.4rc40\\lib\\tools\\Python\\mcdisplay\\webgl\..\..\mccodelib\instrparser.py", line 223, in __init__
    raise Exception('InstrObjectConstructor: parsetreeroot must be a Node of type "instrdeftree"')
Exception: InstrObjectConstructor: parsetreeroot must be a Node of type "instrdeftree"
</pre>

**Comment by willend** [comment]
Have now  found out what the issue is - we need to do something about backslashes in the instrument filename:

This breaks:
<pre>
Instrument parameters for templateSANS (C:\Users\pwill\McStas\templateSANS.instr)
Set value of instrument parameter lambda (double) [default='6']:
Set value of instrument parameter dlambda (double) [default='0.05']:
Set value of instrument parameter r (double) [default='100']:
Set value of instrument parameter PHI (double) [default='1e-3']:
Set value of instrument parameter Delta_Rho (double) [default='0.6']:
Set value of instrument parameter sigma_abs (double) [default='0.5']:
INSTRUMENT:
Instrument 'templateSANS' (C:\Users\pwill\McStas\templateSANS.instr)
</pre>

Whereas this works:
<pre>
Instrument parameters for templateSANS (templateSANS.instr)
Set value of instrument parameter lambda (double) [default='6']:
Set value of instrument parameter dlambda (double) [default='0.05']:
Set value of instrument parameter r (double) [default='100']:
Set value of instrument parameter PHI (double) [default='1e-3']:
Set value of instrument parameter Delta_Rho (double) [default='0.6']:
Set value of instrument parameter sigma_abs (double) [default='0.5']:
Set value of instrument parameter pmul (double) [default='1']:
INSTRUMENT:
Instrument 'templateSANS' (templateSANS.instr)
</pre>

**Comment by willend** [comment]
- so the parsetab INSTRKW needs to be slightly expanded... :-) Could you show me how this is done @climbcat ?

**Comment by willend** [comment]
Fixed
