### ISSUE TITLE
mcplot-pyqtgraph: 2D plots sometimes get wrong axis defintions 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#390]
Two issues:
A) It seems the recent restructuring lost our capability to plot a single datafile:
<pre>
mcplot AutoTOFLend_1485691480.t_L 
mcplot error: __init__() missing 1 required positional argument: 'data_handle'
Traceback (most recent call last):
  File "/Applications/McStas-2.4rc51.app/Contents/Resources/mcstas/2.4rc51/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 368, in <module>
    main(args)
  File "/Applications/McStas-2.4rc51.app/Contents/Resources/mcstas/2.4rc51/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 359, in main
    raise e
  File "/Applications/McStas-2.4rc51.app/Contents/Resources/mcstas/2.4rc51/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 338, in main
    loader.load()
  File "/Applications/McStas-2.4rc51.app/Contents/Resources/mcstas/2.4rc51/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 795, in load
    exit_node = control.process(args=args)
  File "/Applications/McStas-2.4rc51.app/Contents/Resources/mcstas/2.4rc51/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/flowchart.py", line 86, in process
    next = node.process(args)
  File "/Applications/McStas-2.4rc51.app/Contents/Resources/mcstas/2.4rc51/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/flowchart.py", line 67, in process
    self.result = self.fct(args)
  File "/Applications/McStas-2.4rc51.app/Contents/Resources/mcstas/2.4rc51/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 670, in load_monitor
    root = PNSingle()
TypeError: __init__() missing 1 required positional argument: 'data_handle'
</pre>

B) With the below dataset (via mccode.sim/folder), something goes haywire with the wavelength and time axes... :-)

Plots from mcplot.pl and mcplot-pyqtgraph are here:

<img width="1433" alt="terminalscreensnapz001" src="https://cloud.githubusercontent.com/assets/8593355/22404030/1d0d7d52-e628-11e6-941d-eadceb5a5273.png">

Dataset is 
[AutoTOFL.zip](https://github.com/McStasMcXtrace/McCode/files/737509/AutoTOFL.zip) and contains both a single plot file and a full simfolder dataset.

**Comment by climbcat** [comment]
The first one was simple, but the issue with the axes being centered, is unrelated. It must have been there for a while without us noticing it (maybe even since we did the color map stuff?).

**Comment by climbcat** [comment]
pqtg is indeed behaving very strangely when it comes to sizing subplots and even images within plots, on my system. The scaling of the monitor windows are completely off when compared to desktop windows. The code to scale and translate doesn't work properly, and the auto-sizing of the pqtg plots doesn't work properly. Going to have to look into this.

**Comment by willend** [comment]
OK for the single files, keeping the other part of the issue here

**Comment by climbcat** [comment]
We probably need to work on this in parallel, hope we can fix it. It has something to do with the way pqtg works.

**Comment by willend** [comment]
I had a further look - it seems the problem can be isolated to 2D monitor data produced by Monitor_nD, so something might be slightly different in the input data... High hopes... :-)

**Comment by willend** [comment]
The plot thickens: Not necessarily Monitor_nD, but a matter of handling the image "translation" in plot_Data2D when the "origin" of the axis not on the plot... The line

<pre>
img.translate(-datashape[0]/2, -datashape[1]/2)
</pre>

much too simple and simply wrong in cases where the origin is not meant to be at the centre of the plot... :-)

**Comment by climbcat** [comment]
Ok, very cool:-) Lets put the proper formula in (wondering what that might be..)

**Comment by willend** [comment]
Found the fix:
1) The image "scale" defines the axes so that the with of a pixel becomes right (i.e. dx, dy)
2) Translation should be of the "first pixel" (i.e. a kind of image origin) is in original pixel units - so min(x)/dx, min(y)/dy
3) The "automatic" image scaling went haywire - so now doing the scaling independently for X and Y based on the axis values from the monitor file.

Closing, finally! :-)
