### ISSUE TITLE
Issues with NeXus + MPI on macOS 10.12

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#401]
This type of error has (re-)appeared on macOS:

<pre>
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node pkwi-mbp2016 exited on signal 6 (Abort trap: 6).
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Applications/McStas-2.4rc58.app/Contents/Resources/mcstas/2.4rc58/bin/../tools/Python/mcrun/mcrun.py", line 363, in <module>
    main()
  File "/Applications/McStas-2.4rc58.app/Contents/Resources/mcstas/2.4rc58/bin/../tools/Python/mcrun/mcrun.py", line 351, in main
    mcstas.run()
  File "/Applications/McStas-2.4rc58.app/Contents/Resources/mcstas/2.4rc58/tools/Python/mcrun/mccode.py", line 204, in run
    return self.runMPI(args, pipe, override_mpi)
  File "/Applications/McStas-2.4rc58.app/Contents/Resources/mcstas/2.4rc58/tools/Python/mcrun/mccode.py", line 221, in runMPI
    return Process(binpath).run(args, pipe=pipe)
  File "/Applications/McStas-2.4rc58.app/Contents/Resources/mcstas/2.4rc58/tools/Python/mcrun/mccode.py", line 79, in run
    raise ProcessException(self.executable, args, retval)
mccode.ProcessException: Got exit status 134 from "mpirun -np 8 ./NMX_chop_Def_Curv_Parab_Focus_chop_Mantid.out --ncount 200000000.0 --dir NMX_chop_Def_Curv_Parab_Focus_chop_Mantid_20170203_111229 --format NeXus"
</pre>

**Comment by willend** [comment]
Looks to be specific to instruments using Monitor_nD with options="mantid...", i.e. event list storing. 

Is even a problem when running single-core MPI, so not a matter of overlapping writes...

**Comment by willend** [comment]
Downgrading gcc (e.g. via anaconda) seems to help...

**Comment by willend** [comment]
It turns out that this is (like originally) an issue with cc/clang/llvm-gcc on OS X. The solution likely is to bundle compiler, mpi etc.

**Comment by willend** [comment]
Solved, to the extend that the user has to manually install NeXus libs... But now we at least run with an embedded gcc from anaconda that will work OK.
