### ISSUE TITLE
mcrun-py: Triplecheck that MCSTAS_CFLAGS_OVERRIDE is honoured

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#422]
<pre>
     mccode-r.h:663:18: fatal error: napi.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/Applications/McStas-2.4rc81.app/Contents/Resources/mcstas/2.4rc81/bin/../tools/Python/mcrun/mcrun.py", line 358, in <module>
    main()
  File "/Applications/McStas-2.4rc81.app/Contents/Resources/mcstas/2.4rc81/bin/../tools/Python/mcrun/mcrun.py", line 280, in main
    mcstas.prepare(options)
  File "/Applications/McStas-2.4rc81.app/Contents/Resources/mcstas/2.4rc81/tools/Python/mcrun/mccode.py", line 173, in prepare
    Process(options.cc).run(args)
  File "/Applications/McStas-2.4rc81.app/Contents/Resources/mcstas/2.4rc81/tools/Python/mcrun/mccode.py", line 80, in run
    raise ProcessException(self.executable, args, retval)
mccode.ProcessException: Got exit status 1 from "gcc -o ./templateSANS_Mantid.out ./templateSANS_Mantid.c -lm -UUSE_MPI -g -lm -O2 -DUSE_NEXUS -lNeXus -I/usr/local/nexus "
</pre>

If the printed command
<pre>gcc -o ./templateSANS_Mantid.out ./templateSANS_Mantid.c -lm -UUSE_MPI -g -lm -O2 -DUSE_NEXUS -lNeXus -I/usr/local/nexus</pre>
is pasted back in the terminal, compilation happens OK??

**Comment by willend** [comment]
Can be closed if one is clever enough to use a proper include path... /usr/local/include/nexus is the location on OS X...
