### ISSUE TITLE
mcdisplay-pyqtgraph: Time of flight tracing crashes when comp name begins with t

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#444]
mcdisplay-pyqtgraph --tof crashes with the following error message when one more components is named something that begins with a diminutive 't' (example is attached):
[template_simple.txt](https://github.com/McStasMcXtrace/McCode/files/951591/template_simple.txt)
 

starting particle parsing
ended particle parsing
list index out of range
Traceback (most recent call last):
  File "/usr/share/mcstas/2.4pre01/tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 568, in <module>
    raise e
  File "/usr/share/mcstas/2.4pre01/tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 563, in <module>
    main(args)
  File "/usr/share/mcstas/2.4pre01/tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 542, in main
    sys.exit(gui.run_ui_tof(instrument, raybundle.rays))
  File "/usr/share/mcstas/2.4pre01/tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 417, in run_ui_tof
    plot_1d_tof_rays(instr, rays, plt)
  File "/usr/share/mcstas/2.4pre01/tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 83, in plot_1d_tof_rays
    g.transform = [c.transform for c in instr.components if c.name == g.compname][0]
IndexError: list index out of range

**Comment by willend** [comment]
.... fixed
