### ISSUE TITLE
mcgui in McStas 2.4 - configuration dialogue crashes

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#470]
The error message is along the lines of:
<pre>
/usr/share/mcstas/2.4/tools/Python/mcgui/../mccodelib/mccode_config.py:76: SyntaxWarning: name 'configuration' is used prior to global declaration
  global configuration
user config does not exist: /home/farhi/.mcstas/2.4/mccode_config.json
Traceback (most recent call last):
  File "/usr/share/mcstas/2.4/bin/../tools/Python/mcgui/mcgui.py", line 615, in handleConfiguration
    self.view.showConfigDialog()
  File "/usr/share/mcstas/2.4/tools/Python/mcgui/viewclasses.py", line 171, in showConfigDialog
    dlg = McConfigDialog()
  File "/usr/share/mcstas/2.4/tools/Python/mcgui/viewclasses.py", line 1007, in __init__
    prefix = mccode_config.get_mccode_prefix()
AttributeError: 'module' object has no attribute 'get_mccode_prefix'
</pre>

**Comment by willend** [comment]
The solution is to:
Deb/RPM Linux: install the package mcstas-tools-python-mccodelib-2.4 again
macOS: Place this configuration file in your /Applications//McStas-2.4.app/Contents/Resources/mcstas/2.4/tools/Python/mccodelib/ folder (hint: run 'open $MCSTAS' from the terminal and you should get a finder window in /Applications//McStas-2.4.app/Contents/Resources/mcstas/2.4/)
Windows: Place this configuration file in your C:\mcstas-2.4\lib\tools\Python\mccodelib folder (hint: run 'start $MCSTAS' from the terminal and you should get an explorer window in C:\mcstas-2.4\lib)
