### ISSUE TITLE
Debian 8.8 issue with mcplot-pyqtgraph - pyqtgraph version related?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#476]
On a Debian 8.8 systems (elearn1.fysik.dtu.dk and mcxtrace-01.risoe.dk) 
<pre>
mcstas-2.4 env ~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.8 (jessie)
Release:	8.8
Codename:	jessie
</pre>

I get the following behaviour from mcplot-pyqtgrahph:
<pre>
mcstas-2.4 env ~ $ mcplot BNL_H8_20170520_121646/
/usr/share/mcstas/2.4/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mccode_config.py:76: SyntaxWarning: name 'configuration' is used prior to global declaration
  global configuration
Active colormap: jet
mcplot error: setStyle() takes no keyword arguments
Traceback (most recent call last):
  File "/usr/share/mcstas/2.4/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 373, in <module>
    main(args)
  File "/usr/share/mcstas/2.4/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 364, in main
    raise e
  File "/usr/share/mcstas/2.4/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 354, in main
    plotter.runplot()
  File "/usr/share/mcstas/2.4/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 41, in runplot
    plot_node(node, plt_layout, flipper)
  File "/usr/share/mcstas/2.4/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 119, in plot_node
    viewbox_lst.append(add_plot(layout, data_lst[i], i, n, viewmodel.logstate(), viewmodel.legendstate(), viewmodel.cmapindex()))
  File "/usr/share/mcstas/2.4/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 311, in add_plot
    view_box, lyt = plot_Data2D(data, plt, log=log, legend=legend, icolormap=icolormap, verbose=verbose, legend_fontsize=legend_fontsize)
  File "/usr/share/mcstas/2.4/tools/Python/mcplot/pyqtgraph/plotfuncs.py", line 221, in plot_Data2D
    colorbar.axes['top']['item'].setStyle(showValues=False)
TypeError: setStyle() takes no keyword arguments
/usr/share/mcstas/2.4/bin/mcplot: line 36: 36040 Segmentation fault      python3 ${LIB}/${TOOL}.py $*
</pre>

The version of pyqtgraph is this one
<pre>
mcstas-2.4 env ~ $ dpkg -l |grep python3-pyqtgraph
ii  python3-pyqtgraph                            0.9.8-3                              all          Scientific Graphics and GUI Library for Python 3
mcstas-2.4 env ~ $ 
</pre>

Ubuntu 16.04 LTS ships 0.9.10-5 which works.

**Comment by willend** [comment]
Cherry-picking python3-pyqtgraph from testing (currently v. 0.10.0-1) is a workaround - get it here:
https://packages.debian.org/stretch/python3-pyqtgraph
