### ISSUE TITLE
mcplot-pyqtgraph / mcplotloader misses + in a regex relating to yxlimits. (Check for other similar issues)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#537]
The attached file makes mcplot-pyqtgraph throw up because it has a + in the xylimits:
<pre># xylimits: 0 5e+06 0.5 100</pre>

- resulting in a fatal runtime error:
<pre>
Data2D load error.
mcplot error: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 379, in <module>
    main(args)
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 369, in main
    raise e
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 359, in main
    plotter.runplot()
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 41, in runplot
    plot_node(node, plt_layout, flipper)
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 110, in plot_node
    data_lst = node.getdata_lst()
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 58, in getdata_lst
    return [self._data_handle.getdata()]
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 73, in getdata
    self._data = self._load_fct()
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 416, in <lambda>
    data = DataHandle(load_fct=lambda m=monitorfile: load(monfile=m))
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 411, in load
    data = _parse_2D_monitor(text)
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 395, in _parse_2D_monitor
    raise e
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcplot/pyqtgraph/../../mccodelib/mcplotloader.py", line 346, in _parse_2D_monitor
    data.xlimits = (float(m.group(1)), float(m.group(2)), float(m.group(3)), float(m.group(4)))
AttributeError: 'NoneType' object has no attribute 'group'
</pre>

I think we should make these types of errors non-fatal somehow - it leaves the user in the position where a whole dataset does not plot because of one char of one file...

[TofLambdaSampleZoomOut.dat.txt](https://github.com/McStasMcXtrace/McCode/files/1275363/TofLambdaSampleZoomOut.dat.txt)

**Comment by willend** [comment]
@climbcat example file above

**Comment by climbcat** [comment]
It appears that @ebknudsen already fixed this in november -> 14d823270d369fe7626b646664dfa1a3c84e40b6

**Comment by willend** [comment]
OK, closing
