### ISSUE TITLE
McCode tools: mcrun/mxrun unhelpful error message for mistyped parameters 

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#542]

**Comment by willend** [comment]
@ebknudsen to comment further, @climbcat to implement

**Comment by willend** [comment]
@ebknudsen could you detail a little more on this issue?

Presently I can not reproduce using 2.4.1, I do get a "normal" error message both in the mcrun.pl and mcrun Python cases:

`mcstas-2.4.1 env tmp $ mcrun.pl BNL_H8.instr lambdax=4,5 -N2
/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/mcrun.pl: reading local mcstas configuration from /Users/pkwi/.mcstas/mccode_config.perl
*** No directory given - placing data in BNL_H8_20180104_152645 ***
BNL_H8.out --dir=BNL_H8_20180104_152645/0 --format=PGPLOT --ncount=1000000 lambdax=4
Error: unrecognized parameter lambdax (mcparseoptions)
mcrun: Exit #1 due to error returned by simulation program (BNL_H8.out=256)
BNL_H8.out --dir=BNL_H8_20180104_152645/1 --format=PGPLOT --ncount=1000000 lambdax=5
Error: unrecognized parameter lambdax (mcparseoptions)
mcrun: Exit #2 due to error returned by simulation program (BNL_H8.out=256)
Output file: 'BNL_H8_20180104_152645/mccode.dat'
Output parameters: lambdax 
mcrun: Error: Simulation BNL_H8.out BNL_H8_20180104_152645 returned 2 invalid scan steps,
       which intensity was set to zero in data file mccode.dat.
mcstas-2.4.1 env tmp $ mcrun BNL_H8.instr lambdax=4,5 -N2
loading user configuration from /Users/pkwi/.mcstas/2.4.1/mccode_config.json
INFO: No output directory specified (--dir)
INFO: Using directory: "BNL_H8_20180104_152705"
INFO: Using existing binary: ./BNL_H8.out
INFO: ===
INFO: Running Scanner, result file is "BNL_H8_20180104_152705/mccode.dat"
INFO: lambdax: 4.000000
Traceback (most recent call last):
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcrun/mcrun.py", line 372, in <module>
    main()
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcrun/mcrun.py", line 352, in main
    scanner.run()
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/tools/Python/mcrun/optimisation.py", line 240, in run
    out = self.mcstas.run(pipe=True, extra_opts={'dir': current_dir})
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 210, in run
    return self.runMPI(args, pipe, override_mpi)
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 229, in runMPI
    return Process(binpath).run(args, pipe=pipe)
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 80, in run
    raise ProcessException(self.executable, args, retval)
mccode.ProcessException: Got exit status 1 from "./BNL_H8.out --ncount 1000000 --dir BNL_H8_20180104_152705/0 --format McStas lambdax=4"
mcstas-2.4.1 env tmp $ `

**Comment by willend** [comment]
@ebknudsen ? :-)

**Comment by ebknudsen** [comment]
Well that's exactly the point :-). The perl version mentions what the problem is:
''''
Error: unrecognized parameter lambdax (mcparseoptions)
''''
whereas the python version merely states the it tries to do the first scan step and then exits with a python error trace, which to a casual user can mean anything.

**Comment by ebknudsen** [comment]
Granted it does produce "an error message" - I meant to write "the helpful error message", or something to that effect.

**Comment by climbcat** [comment]
This should be fixed now. If the Popen call returns a non-zero return value, the process' stderr is printed to the terminal, and python exits with error code -1

**Comment by climbcat** [comment]
Fixed: Python now returns the same non-zero value as mcstas/mxtrace did.
