### ISSUE TITLE
mcplot-matplotlib --html fails on macOS and Windows 10

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#581]
mcplot-matplotlib --html fails on my mac with the below error message

<pre>
mcstas-2.5rczyx env tmp $ mcplot-matplotlib --html BNL_H8_20180109_155910
mcplot error: Object of type 'ndarray' is not JSON serializable
Traceback (most recent call last):
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/bin/../tools/Python/mcplot/matplotlib/mcplot.py", line 341, in <module>
    main(args)
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/bin/../tools/Python/mcplot/matplotlib/mcplot.py", line 328, in main
    raise e
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/bin/../tools/Python/mcplot/matplotlib/mcplot.py", line 312, in main
    plotter.html_node(rootnode, open('%s.html' % os.path.splitext(simfile)[0], 'w'))
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/bin/../tools/Python/mcplot/matplotlib/mcplot.py", line 178, in html_node
    mpld3.save_html(pylab.gcf(), fileobj)
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/miniconda3/lib/python3.6/site-packages/mpld3/_display.py", line 453, in save_html
    fileobj.write(fig_to_html(fig, **kwargs))
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/miniconda3/lib/python3.6/site-packages/mpld3/_display.py", line 251, in fig_to_html
    figure_json=json.dumps(figure_json, cls=NumpyEncoder),
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/miniconda3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/miniconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/miniconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/miniconda3/lib/python3.6/site-packages/mpld3/_display.py", line 138, in default
    return json.JSONEncoder.default(self, obj)
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/miniconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ndarray' is not JSON serializable
</pre>

I have experimented with taking mpld3 (and dependencies) in both via conda and pip, same issue

**Comment by willend** [comment]
It seems the same problem is present on Windows 10 (where it seems one needs to downgrade anaconda to 3.5 to have mpld3 available)

<pre>
C:\Users\pwill>mcplot-matplotlib --html BNL_H8_20180109_162220
mcplot error: array([0.25]) is not JSON serializable
Traceback (most recent call last):
  File "C:\\mcstas-2.5xxy\\lib\\tools\\Python\\mcplot\\matplotlib\\mcplot.py", line 309, in <module>
    main(args)
  File "C:\\mcstas-2.5xxy\\lib\\tools\\Python\\mcplot\\matplotlib\\mcplot.py", line 298, in main
    raise e
  File "C:\\mcstas-2.5xxy\\lib\\tools\\Python\\mcplot\\matplotlib\\mcplot.py", line 288, in main
    plotter.html_node(rootnode, open('%s.html' % os.path.splitext(simfile)[0], 'w'))
  File "C:\\mcstas-2.5xxy\\lib\\tools\\Python\\mcplot\\matplotlib\\mcplot.py", line 174, in html_node
    mpld3.save_html(pylab.gcf(), fileobj)
  File "C:\mcstas-2.5xxy\miniconda3\lib\site-packages\mpld3\_display.py", line 453, in save_html
    fileobj.write(fig_to_html(fig, **kwargs))
  File "C:\mcstas-2.5xxy\miniconda3\lib\site-packages\mpld3\_display.py", line 251, in fig_to_html
    figure_json=json.dumps(figure_json, cls=NumpyEncoder),
  File "C:\mcstas-2.5xxy\miniconda3\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\mcstas-2.5xxy\miniconda3\lib\json\encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\mcstas-2.5xxy\miniconda3\lib\json\encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "C:\mcstas-2.5xxy\miniconda3\lib\site-packages\mpld3\_display.py", line 138, in default
    return json.JSONEncoder.default(self, obj)
  File "C:\mcstas-2.5xxy\miniconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([0.25]) is not JSON serializable
C:\Users\pwill>
</pre>

**Comment by willend** [comment]
Annoying - just found something at the end of
https://github.com/mpld3/mpld3/issues/193 ...

It does work to add 
<pre>
elif isinstance(obj, (numpy.ndarray,)):
        return obj.tolist()
to /mpld3/_display.py: NumpyEncoder
</pre>

- but unfortunately it looks like mpld3 is a dormant code... - see https://github.com/mpld3/mpld3/blob/master/README.md

**Comment by willend** [comment]
We could of course in principle clone and build packages ourselves... But that requires a little thinking I think.

**Comment by willend** [comment]
For a start I've cloned the repo to https://github.com/McStasMcXtrace/mpld3 and applied the above patch.

**Comment by willend** [comment]
I can further confirm that the patch solves the issue on both macOS and Windows... So likely the mpld3 on Debian/Ubuntu simply has this patch already, as indicated by the debian package version below...:

<pre>
mcstas@mcstas-virtual-machine:~$ dpkg -l python-mpld3 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  python-mpld3   0.3git+20140 all          D3 viewer for matplotlib
mcstas@mcstas-virtual-machine:~$ 
</pre>

**Comment by willend** [comment]
@ebknudsen you and I should have a discussion about this one - I am inclined to simply drop the --html option as we have other ways of doing McCode plots for the browser

**Comment by willend** [comment]
ping

**Comment by willend** [comment]
I think turning off this functionality on macOS / windows should be OK.
