### ISSUE TITLE
mcplot-matplotlib can not do "sweep" plots across scans

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#584]
Fails with meta-click on mac os x with
<pre>
Traceback (most recent call last):
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/miniconda3/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/miniconda3/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/bin/../tools/Python/mcplot/matplotlib/mcplot.py", line 141, in _keypress_proxy
    keypress(event, back_cb=self.back_cb, replot_cb=self.replot_cb, togglelog_cb=self._flip_log)
  File "/Applications/McStas-2.5rczyx.app/Contents/Resources/mcstas/2.5rczyx/bin/../tools/Python/mcplot/matplotlib/mcplot.py", line 181, in keypress
    key = event.key.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
</pre>

**Comment by climbcat** [comment]
This works fine on my system - we will need to debug this on the "problem OS" in question.

**Comment by willend** [comment]
Works with ctrl+click, so the help ought to be corrected on this point wrt. macOS:
<pre>
q              - quit
F1/h           - help
l              - toggle log
p              - save ps
d              - save pdf
n              - save png
j              - save jpg
s              - native save dialog
F5             - replot
click          - display subplot
right-click/b  - back
Meta + click   - sweep monitors
</pre>
