### ISSUE TITLE
Support for ÆØÅ (etc.) in python tools

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#616]
Even though "one should not use" these characters in instrument files, users will continue to do so... :-) 

We should find a stable solution for mcgui (where the editor prevents from opening). Example instrument attached with a Å in the doc strings...
[BNL_H8_scandi.instr.txt](https://github.com/McStasMcXtrace/McCode/files/2025643/BNL_H8_scandi.instr.txt)

**Comment by climbcat** [comment]
Alright, yes I understand why people would love to use Å...

**Comment by willend** [comment]
In mcdisplay-webgl on Windows a user has seen:
<pre>

'charmap' codec can't encode character '\u2026' in position 34: character maps to <undefined>
Traceback (most recent call last):
 File "C:\\mcstas-2.4.1\\lib\\tools\\Python\\mcdisplay\\pyqtgraph\\mcdisplay.py", line 572, in <module>
   raise e
 File "C:\\mcstas-2.4.1\\lib\\tools\\Python\\mcdisplay\\pyqtgraph\\mcdisplay.py", line 567, in <module>
   main(args)
 File "C:\\mcstas-2.4.1\\lib\\tools\\Python\\mcdisplay\\pyqtgraph\\mcdisplay.py", line 533, in main
   instrument = reader.read_instrument()
 File "C:\\mcstas-2.4.1\\lib\\tools\\Python\\mcdisplay\\pyqtgraph\..\..\mccodelib\mcdisplayutils.py", line 61, in read_instrument
   self.pipeman.join()
 File "C:\\mcstas-2.4.1\\lib\\tools\\Python\\mcdisplay\\pyqtgraph\..\..\mccodelib\pipetools.py", line 332, in join
   raise self.reader.exc_obj
 File "C:\\mcstas-2.4.1\\lib\\tools\\Python\\mcdisplay\\pyqtgraph\..\..\mccodelib\pipetools.py", line 266, in run
   self.current.add_line(stdoutdata)
 File "C:\\mcstas-2.4.1\\lib\\tools\\Python\\mcdisplay\\pyqtgraph\..\..\mccodelib\pipetools.py", line 77, in add_line
   print(line.rstrip('\n'))
 File "C:\mcstas-2.4.1\miniconda3\lib\encodings\cp850.py", line 19, in encode
   return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2026' in position 34: character maps to <undefined>
</pre>
with the attached instr file - which behaves OK on a Mac
[PC_freia_choppers_simpleguide_may18_mod.instr.txt](https://github.com/McStasMcXtrace/McCode/files/2035298/PC_freia_choppers_simpleguide_may18_mod.instr.txt)

Correcting the included Å's to AA one gets this version which works OK:
[PC_freia_choppers_simpleguide_may18_mod_PW.instr.txt](https://github.com/McStasMcXtrace/McCode/files/2035304/PC_freia_choppers_simpleguide_may18_mod_PW.instr.txt)

**Comment by willend** [comment]
Found some good hints here:
https://docs.python.org/3/howto/unicode.html

**Comment by climbcat** [comment]
On my system, I can run and display both examples with Å and all.
