### ISSUE TITLE
mcdisplay (py) issues - parsing/utf8 and 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#639]
Two issues present themselves with the attached instruments (FREIA_model_july18.instr includes Å chars, these are removed in REIA_model_july18_PW.instr)

1) Å char not allowed in printf's
<pre>
mcdisplay FREIA_model_july18.instr p4=1
'ascii' codec can't decode byte 0xc3 in position 4294: ordinal not in range(128)
Traceback (most recent call last):
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 572, in <module>
    raise e
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 567, in <module>
    main(args)
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 533, in main
    instrument = reader.read_instrument()
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/pyqtgraph/../../mccodelib/mcdisplayutils.py", line 61, in read_instrument
    self.pipeman.join()
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/pyqtgraph/../../mccodelib/pipetools.py", line 332, in join
    raise self.reader.exc_obj
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/pyqtgraph/../../mccodelib/pipetools.py", line 263, in run
    stdoutdata = process.stdout.readline()
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../miniconda3/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4294: ordinal not in range(128)
</pre>
- Fix should probably be along the lines of https://github.com/McStasMcXtrace/McCode/commit/b63bdd9999b2076cfec945371d2506ba2771dca9

2) Once we are past 1) above, pyqtgraph mcdisplay works OK, but mcdisplay-webgl breaks with:
<pre>
mcdisplay-webgl FREIA_model_july18_PW.instr p4=1
.... (many lines skipped)

starting particle parsing
ended particle parsing
'NoneType' object has no attribute 'add'
Traceback (most recent call last):
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 200, in <module>
    raise e
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 195, in <module>
    main(args)
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 168, in main
    write_browse(instrument, raybundle, dirname)
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 123, in write_browse
    _write_html(instrument, html_filepath, first=args.first, last=args.last, invcanvas=args.invcanvas)
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/webgl/mcdisplay.py", line 86, in _write_html
    box = instrument.get_boundingbox(first, last)
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/webgl/../../mccodelib/instrgeom.py", line 43, in get_boundingbox
    box = c.get_tranformed_bb()
  File "/Applications/McStas-2.4.1.app/Contents/Resources/mcstas/2.4.1/bin/../tools/Python/mcdisplay/webgl/../../mccodelib/instrgeom.py", line 103, in get_tranformed_bb
    box = d.get_boundingbox(self.transform).add(box)
AttributeError: 'NoneType' object has no attribute 'add'
</pre>

[FREIA.zip](https://github.com/McStasMcXtrace/McCode/files/2197246/FREIA.zip)

**Comment by willend** [comment]
It helps a little to give 
<pre>
encoding='utf-8'
</pre>

as part of the Popen calls in pipetools...

**Comment by climbcat** [comment]
Currently, no target folder is written by mcrun when I run mcdisplay - seems to be an unrelated issue.

**Comment by climbcat** [comment]
Right now, the "non _PW" file displays fine on my system.
