### ISSUE TITLE
mcplot issues with specific dataset

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#652]
The attached, lightly modified instrument: 
[templateTAS.instr.txt](https://github.com/McStasMcXtrace/McCode/files/2391454/templateTAS.instr.txt)

which needs this crystal definition: 
[BCC_fake.lau.txt](https://github.com/McStasMcXtrace/McCode/files/2391457/BCC_fake.lau.txt)

can be run with the commandline
<pre>
mcrun  -c templateTAS.instr QK=0 QH=1.9,2.1 QL=0 SX=1 Sqw_coh=BCC_fake.lau -N21 -n1e4
</pre>

which produces a dataset like this one:
[templateTAS_20180918_084341.zip](https://github.com/McStasMcXtrace/McCode/files/2391466/templateTAS_20180918_084341.zip)

- With McStas 2.4.1, sweep plotting does not work correctly (at least on mac) with the last monitor. If sweep-clicking the second-to-last, the expected monitor output from the last monitor appears

- With a fresh build from master the plotter instead simply fails with
<pre>
mcplot templateTAS_20180918_084341

q              - quit
p              - save png
s              - save svg
l              - log toggle
t              - textinfo toggle
c              - cycle colormap
F1/h           - help
F5             - replot
click          - display subplot
right-click/b  - back
Meta + click   - sweep monitors
x              - expand subplots
mcplot error: list index out of range
Traceback (most recent call last):
  File "/Applications/McStas-2.5mdanse.app/Contents/Resources/mcstas/2.5mdanse/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 67, in <module>
    main(args)
  File "/Applications/McStas-2.5mdanse.app/Contents/Resources/mcstas/2.5mdanse/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 57, in main
    raise e
  File "/Applications/McStas-2.5mdanse.app/Contents/Resources/mcstas/2.5mdanse/bin/../tools/Python/mcplot/pyqtgraph/mcplot.py", line 51, in main
    plotter.runplot()
  File "/Applications/McStas-2.5mdanse.app/Contents/Resources/mcstas/2.5mdanse/tools/Python/mcplot/pyqtgraph/../../mccodelib/pqtgfrontend.py", line 59, in runplot
    plot_node(node, self.plot_func, plt_layout, viewmodel)
  File "/Applications/McStas-2.5mdanse.app/Contents/Resources/mcstas/2.5mdanse/tools/Python/mcplot/pyqtgraph/../../mccodelib/pqtgfrontend.py", line 160, in plot_node
    vn_dict_ctrlclick[viewbox_lst[i]] = sec_lst[i]
IndexError: list index out of range
</pre>

**Comment by willend** [comment]
Issue reproduced also on Ubuntu 18.04 install
