### ISSUE TITLE
get_deps_win is likely outdated

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#863]
Some of the required packages for the windows build seem to be outdated and/or not existing anymore.
e.g. wine64, nsis

**Comment by willend** [comment]
Ouch. On which Linux did you attempt the build? I guess the dependencies listed were those that worked well with Ubuntu 16.04.

I can try an 18.04 for a second opinion?

**Comment by willend** [comment]
At first glance this looks OK on 18.04:

![Screenshot 2019-09-25 at 10 33 19](https://user-images.githubusercontent.com/8593355/65583752-11dcc600-df80-11e9-9584-bfe2c838f049.png)

**Comment by willend** [comment]
Ends with a wine/windows based dialogue that wants to download stuff which looks to never arrive... Have cancelled that and am now running the build script for mcstas

**Comment by willend** [comment]
With the last couple of commits on master I can produce what looks to be functional metapackage executable for McStas on Ubuntu 18.04. - I have put one here: http://tmp.mccode.org/McStas-Metapackage-2.6beta-win64.exe

I will now proceed to do the same type of build for McXtrace

**Comment by willend** [comment]
There seems to currently be an issue with building the McXtrace code generator for windows - I get the following which relates to the build of mcformat (which IMHO could/shuld become obsoleted on both mcstas and mcxtrace subprojects)

```
/usr/bin/cmake -H/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work -B/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/CMakeFiles /home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work'
make -f CMakeFiles/mxformat.dir/build.make CMakeFiles/mxformat.dir/depend
make[2]: Entering directory '/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work'
cd /home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work /home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work /home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work /home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work /home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/CMakeFiles/mxformat.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work'
make -f CMakeFiles/mxformat.dir/build.make CMakeFiles/mxformat.dir/build
make[2]: Entering directory '/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work'
[  6%] Building C object CMakeFiles/mxformat.dir/work/src/mcformat.c.obj
/usr/bin/x86_64-w64-mingw32-gcc -DFLAVOR=\"mcxtrace\" -DFLAVOR_FMT=\"mxformat\" -DFLAVOR_LIB=\"xlib\" -DFLAVOR_UPPER=\"MCXTRACE\" -DHAVE_FDOPEN=HAVE_FDOPEN -DHAVE_QSORT=HAVE_QSORT -DHAVE_STRCASECMP=HAVE_STRCASECMP -DMCCODE_BUGREPORT=\"www.mcxtrace.org\" -DMCCODE_LIBENV=\"MCXTRACE\" -DMCCODE_NAME=\"McXtrace\" -DMCCODE_PARTICLE=\"xray\" -DMCCODE_PROJECT=2 -DMCCODE_STRING="\"McXtrace 1.5beta - Sep. 25, 2019\"" -DMCCODE_TARNAME=\"mcxtrace\" -DMCCODE_URL=\"\" -DMCCODE_VERSION=\"1.5beta\" -DNAME=\"McXtrace\" -Drandom=rand -Dsrandom=srand @CMakeFiles/mxformat.dir/includes_C.rsp  -o CMakeFiles/mxformat.dir/work/src/mcformat.c.obj   -c /home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/work/src/mcformat.c
In file included from /home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/work/src/mcformat.c:60:0:
/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/work/src/../lib/share/mccode-r.c: In function <E2><80><98>mcuse_dir<E2><80><99>:
/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/work/src/../lib/share/mccode-r.c:52:27: warning: implicit declaration of function <E2><80><98>_mkdir<E2><80><99>; did you mean <E2><80><98>mkdir<E2><80><99>? [-Wimplicit-function-declaration]
 # define  mkdir( D, M )   _mkdir( D )
                           ^
/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/work/src/../lib/share/mccode-r.h:219:27: note: in definition of macro <E2><80><98>MPI_MASTER<E2><80><99>
 #define MPI_MASTER(instr) instr
                           ^~~~~
/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/work/src/../lib/share/mccode-r.c:2072:8: note: in expansion of macro <E2><80><98>mkdir<E2><80><99>
     if(mkdir(mcdirname, 0777)) {
        ^~~~~
/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/work/src/mcformat.c: In function <E2><80><98>mcformat_usedir<E2><80><99>:
/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work/work/src/mcformat.c:955:42: error: macro "mkdir" requires 2 arguments, but only 1 given
   if(!mcdisable_output_files && mkdir(dir))
                                          ^
CMakeFiles/mxformat.dir/build.make:66: recipe for target 'CMakeFiles/mxformat.dir/work/src/mcformat.c.obj' failed
make[2]: *** [CMakeFiles/mxformat.dir/work/src/mcformat.c.obj] Error 1
make[2]: Leaving directory '/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/mxformat.dir/all' failed
make[1]: *** [CMakeFiles/mxformat.dir/all] Error 2
make[1]: Leaving directory '/home/mcstas/McCode/dist/mcxtrace-NSIS64-1.5beta-mingw64.exe.work'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by willend** [comment]
- Otherwise the metapackage build structure seems OK

**Comment by willend** [comment]
At the current state of master I can build what looks to be an OK metapackage for McXtrace on Ubuntu 18.04. Entire dist folder - can be found here (also contains extra packages etc.)

http://tmp.mccode.org/McXtrace-1.5beta-windows-dist/

**Comment by willend** [comment]
Will test after lunch.

What we ought to update is windows install instructions ala what we have in the repo for McStas, within INSTALL-McXtrace

**Comment by ebknudsen** [comment]
Indeed that is correct. The original reporter is testing some more as well

**Comment by willend** [comment]
OK. Something is fishy with my attempts to run miniconda in a vm here... Will try to roll another Metapackage

**Comment by ebknudsen** [comment]
builds clean on my debian 10 btw.

**Comment by willend** [comment]
Good, that's "half way" then. In my build it seems that miniconda installs to the wrong location presently, still digging

**Comment by willend** [comment]
Hmm, I still have issues installing python-dependencies in Miniconda - could be network issues

```
Starting installation of miniconda to c:\mcxtrace-1.5betaX\miniconda3
...
WARNING: Please wait, process may take several minutes to complete!
 (Pressing [enter] a few times to ensure something is happening is OK)
...
Miniconda install completed, proceeding with McCode dependencies...
Traceback (most recent call last):
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
    return func(*args, **kwargs)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\main_install.py", line 8, in <module>
    from .install import install
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\mcxtrace-1.5betaX\miniconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1354, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1065, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1109, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1120, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1190, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda_package_handling\api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda_package_handling\tarball.py", line 7, in <module>
    import libarchive
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
Traceback (most recent call last):
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
    return func(*args, **kwargs)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\main_install.py", line 8, in <module>
    from .install import install
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\mcxtrace-1.5betaX\miniconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1354, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1065, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1109, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1120, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\exceptions.py", line 1190, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda_package_handling\api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\conda_package_handling\tarball.py", line 7, in <module>
    import libarchive
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "c:\mcxtrace-1.5betaX\miniconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting pyqt5
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyqt5/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyqt5/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyqt5/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyqt5/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyqt5/
  Could not fetch URL https://pypi.org/simple/pyqt5/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pyqt5/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  ERROR: Could not find a version that satisfies the requirement pyqt5 (from versions: none)
ERROR: No matching distribution found for pyqt5
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
...
Press a key below to exit this installation shell...
...
Press any key to continue . . .


```

**Comment by ebknudsen** [comment]
I have since encountered an issue with ispack. it simply just hangs when trying to download "extra files"

**Comment by ebknudsen** [comment]
Some recent updates to the build process and also mcformat.c.in make sure that the build process completes without fault. updates related to this:
0694b8d0bbb439bbd550f9f8dde74ddd24dd35ad 
5424a080d5ef1dd6361d7c4ec9dd71c80dee3316
dea1072b66da9214c3e261f9039ba7247382f595
634df6cfd89458e56f739c93683a0740b6e544f4
6137cf99e1a57e9812ea6b6030dc789ffebebd8a

**Comment by willend** [comment]
Seems a functional set of dependencies can be installed on windows after https://github.com/McStasMcXtrace/McCode/commit/bb8c4424838ec91d6469cc1b0c35748bc9f876b7
