### ISSUE TITLE
2D->1D logic (in case of e.g. nx=1 in PSD_monitor) seems to add a ' ' to generated  xvar

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#895]
From Wim Bouwman's machine:
[det.txt](https://github.com/McStasMcXtrace/McCode/files/3910414/det.txt)

- Plots OK with the more "tolerant" mcplot-pl, but breaks with pyqtgraph/matplotlib plotters:
<pre>
Data1D load error.
mcplot error: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\\mcstas-2.5\\lib\\tools\\Python\\mcplot\\pyqtgraph\\mcplot.py", line 67, in <module>
    main(args)
  File "C:\\mcstas-2.5\\lib\\tools\\Python\\mcplot\\pyqtgraph\\mcplot.py", line 57, in main
    raise e
  File "C:\\mcstas-2.5\\lib\\tools\\Python\\mcplot\\pyqtgraph\\mcplot.py", line 51, in main
    plotter.runplot()
  File "C:\mcstas-2.5\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\pqtgfrontend.py", line 59, in runplot
    plot_node(node, self.plot_func, plt_layout, viewmodel)
  File "C:\mcstas-2.5\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\pqtgfrontend.py", line 141, in plot_node
    viewbox_lst.append(add_plot(layout, node, plot_func, i, n, viewmodel))
  File "C:\mcstas-2.5\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\pqtgfrontend.py", line 350, in add_plot
    view_box, plt_itm = plot_node_func(node, i, plt, options)
  File "C:\mcstas-2.5\lib\tools\Python\mcplot\pyqtgraph\plotfuncs.py", line 26, in plot
    data = node.getdata_idx(i)
  File "C:\mcstas-2.5\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\plotgraph.py", line 70, in getdata_idx
    return self._data_handle.getdata()
  File "C:\mcstas-2.5\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\plotgraph.py", line 90, in getdata
    self._data = self._load_fct()
  File "C:\mcstas-2.5\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\mcplotloader.py", line 314, in <lambda>
    data = DataHandle(load_fct=lambda m=monitorfile: load(monfile=m))
  File "C:\mcstas-2.5\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\mcplotloader.py", line 305, in load
    data = _parse_1D_monitor(text)
  File "C:\mcstas-2.5\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\mcplotloader.py", line 193, in _parse_1D_monitor
    raise e
  File "C:\mcstas-2.5\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\mcplotloader.py", line 154, in _parse_1D_monitor
    data.xvar = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
</pre>

**Comment by willend** [comment]
Fixed, closing
