### ISSUE TITLE
GPUhack: Find options for debugging memory-access issues

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#941]
1) Investigate if nsys gives useful insight.

2) Allinea (arm) DDT? Have asked compute if we can have access to their license from the interactive nodes

**Comment by willend** [comment]
Also look at https://www.pgroup.com/userforum/viewtopic.php?t=6197

**Comment by willend** [comment]
cuda-gdb looks like the thing 
<pre>
cuda-gdb ./a.out 
Traceback (most recent call last):
  File "/usr/share/gdb/python/gdb/__init__.py", line 144, in auto_load_packages
    __import__(modname)
  File "/usr/share/gdb/python/gdb/command/explore.py", line 756, in <module>
    Explorer.init_env()
  File "/usr/share/gdb/python/gdb/command/explore.py", line 135, in init_env
    gdb.TYPE_CODE_RVALUE_REF : ReferenceExplorer,
AttributeError: 'module' object has no attribute 'TYPE_CODE_RVALUE_REF'

NVIDIA (R) CUDA Debugger
9.1 release
Portions Copyright (C) 2007-2017 NVIDIA Corporation
GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./a.out...done.
(cuda-gdb) r
Starting program: /home/dram/instr-builds/a.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffede22700 (LWP 9492)]
[New Thread 0x7fffed621700 (LWP 9493)]
[New Thread 0x7fffecc9d700 (LWP 9494)]
Instrument parameters for ISIS_IMAT (ISIS_IMAT.instr)
Set value of instrument parameter src (double) [default='0']:

Set value of instrument parameter l_min (double) [default='1']:

Set value of instrument parameter l_max (double) [default='10']:

Set value of instrument parameter t_min (double) [default='0']:

Set value of instrument parameter t_max (double) [default='0.2']:

Set value of instrument parameter theta (double) [default='90']:

Searching for TS2.imat in multiple locations... -- 
 - Found in current directory!
Energy == 0.81799 81.799
Time off sec == 1.57 
mod size z == 0.01 
Face == TS2.imat 
Number of Energy Points == 0
TS axis == 0 0
AW axis == 0.094 0.094
Viewport == 0.094 0.094 Moderator size == (0 * 0) m^2 
Dist == 56 (metres) 
Viewport Solid angle == 0 str
Solid angle used == 0 str
Totals:: 0 0 0 
Opening input file '/home/dram/instr-builds/../McStas/mcstas/3.0-dev/data/Na2Ca3Al2F14.laz' (Table_Read_Offset)
Table from file 'Na2Ca3Al2F14.laz' (block 1) is 841 x 18 (x=1:20), constant step. interpolation: linear
  '# TITLE *-Na2Ca3Al2F14-[I213] Courbion, G.;Ferey, G.[1988] Standard NAC cal ...'
PowderN: sample: Reading 841 rows from Na2Ca3Al2F14.laz
PowderN: sample: Read 841 reflections from file 'Na2Ca3Al2F14.laz'
PowderN: sample: Vc=1079.1 [Angs] sigma_abs=0.0117856 [barn] sigma_inc=13.6704 [barn] reflections=Na2Ca3Al2F14.laz

CUDA Exception: Warp Out-of-range Address

Thread 1 "a.out" received signal CUDA_EXCEPTION_5, Warp Out-of-range Address.
[Switching focus to CUDA kernel 0, grid 54, block (0,0,0), thread (96,0,0), device 0, sm 0, warp 1, lane 0]
0x0000000001833990 in getPoint () at ISIS_IMAT.c:6410
6410	  Tpnt=binSearch(TS.nTime-1,TS.Flux[Epnt-1],R);
(cuda-gdb) 
</pre>
@ebknudsen we need to do some sessions with that stuff...
